config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      post 'like'
      delete 'unlike'
    end
  end
  # get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    def increment_views
        self.increment!(:views)
    end
    def increment_likes
        self.increment!(:likes)
    end
    def decrement_likes
        self.decrement!(:likes)
    end
    has_one_attached :image
    validates :title, presence: true, length: { minimum: 5, maximum: 50 } # ограничение введение символов для создания поста
    validates :title, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :init_session

  private

  def init_session
    session[:liked_posts] ||= []
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy like unlike ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])

    unless viewed_post?(@post)
      @post.increment_views
      mark_post_as_viewed(@post)
    end
  end

  

  def viewed_post?(post)
    session[:viewed_posts] ||= []
    session[:viewed_posts].include?(post.id)
  end

  def mark_post_as_viewed(post)
    session[:viewed_posts] << post.id
  end

  def like
    unless liked_post?(@post)
      @post.increment_likes
      mark_post_as_liked(@post)
      respond_to do |format|
        format.html { redirect_to post_url(@post), notice: "You liked this post." }
        format.json { render :show, status: :ok, location: @post }
        format.js   # Добавляем поддержку JS
      end
    else
      respond_to do |format|
        format.html { redirect_to post_url(@post), alert: "You have already liked this post." }
        format.json { render :show, status: :unprocessable_entity, location: @post }
        format.js   # Добавляем поддержку JS
      end
    end
  end

  # DELETE /posts/1/unlike
  def unlike
    if liked_post?(@post)
      @post.decrement_likes
      unmark_post_as_liked(@post)
      respond_to do |format|
        format.html { redirect_to post_url(@post), notice: "You unliked this post." }
        format.json { render :show, status: :ok, location: @post }
        format.js   # Добавляем поддержку JS
      end
    else
      respond_to do |format|
        format.html { redirect_to post_url(@post), alert: "You haven't liked this post yet." }
        format.json { render :show, status: :unprocessable_entity, location: @post }
        format.js   # Добавляем поддержку JS
      end
    end
  end

  def liked_post?(post)
    session[:liked_posts] ||= []
    session[:liked_posts].include?(post.id)
  end

  def mark_post_as_liked(post)
    session[:liked_posts] << post.id
  end

  def unmark_post_as_liked(post)
    session[:liked_posts].delete(post.id)
  end


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Surdo", root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:'nav-link' %>
          <%# <a class="nav-link" href="#">Home</a> %>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", posts_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:'nav-link' %>
          <%# <a class="nav-link" href="#">Link</a> %>
        </li>
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>
        <%# <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
            <li><%= link_to "New Post", new_post_path, class:"dropdown-item" %>
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <%# <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Surdo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="container">
    <h1>My Personal Home Page</h1>
    <p>You can read more about me, or checkout my blog.</p>
    <%= link_to "About Me", about_path, class:"btn btn-secondary" %>
    <%= link_to "Blog", posts_path, class:"btn btn-primary" %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>">
  <h2><%= post.title %></h2>
  <h6><%= pluralize(post.views, "view") %></h6>
  <div>
    <%= post.body %>
  </div>
  <% if post.image.attached? %>
    <div>
      <%= image_tag post.image %>
    </div>
  <% end %>
  <div>
    <%= pluralize(post.likes, "like") %>
  </div>
  
  <div>
    <% if session[:liked_posts].include?(post.id) %>
      <%= button_to 'Unlike', unlike_post_path(post), method: :delete, remote: true %>
    <% else %>
      <%= button_to 'Like', like_post_path(post), method: :post, remote: true %>
    <% end %>
  </div>
  <div>
    <p>Published at: <%= post.created_at.in_time_zone('Tashkent').strftime("%B %d, %Y %H:%M") %></p>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Editing post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Show this post", @post %> |
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h1>Posts</h1>
  <% @posts.each do |post| %>
    <div class="card" style="margin-bottom: 20px; padding: 20px; border: 1px solid #ddd;">
      <table>
        <tr>
          <td style="vertical-align: top;">
            <p><%= post.created_at.strftime("%d.%m.%Y, %H:%M") %></p>
            <h2><%= link_to post.title, post, class: 'post-title-link' %></h2>
            <p><%= pluralize(post.views, "view") %> · <%= pluralize(post.likes, "like") %></p>
            <%# <div>
              link_to 'Show this post', post
            </div> %>
          </td>
          <% if post.image.attached? %>
            <td style="padding-left: 20px; text-align: right;">
              <%= image_tag(post.image, style: "width: 150px; height: auto;") %>
            </td>
          <% end %>
        </tr>
      </table>
    </div>
  <% end %>
  <%= link_to 'New Post', new_post_path %>
</div>


<style>
  .post-title-link {
    color: black;
    text-decoration: none; /* убираем подчеркивание */
  }
</style>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <%= render @post %>

  <div>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
    <%= link_to "Back to posts", posts_path %>

    <%= button_to "Destroy this post", @post, method: :delete %>
  </div>
</div>